# Generated by Django 5.0.4 on 2024-05-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Предложение'),
        ),
    ]
