# Generated by Django 5.0.4 on 2024-05-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='diagnosticcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Медицинское назначение'),
        ),
        migrations.AlterField(
            model_name='medicalresultfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_results/'),
        ),
        migrations.AlterField(
            model_name='medicalresultfile',
            name='file_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание файла'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
